# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 3 } %>
#  timeout: 5000

development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/development.sqlite3

#development:
#  primary:
#    <<: *default
#    database: <%= Rails.application.credentials.dig(:erm, :database) %>
#    username: <%= Rails.application.credentials.dig(:erm,:username) %>
#    host: <%= Rails.application.credentials.dig(:erm,:host) %>
#    password: <%= Rails.application.credentials.dig(:erm, :password) %>
#    migrations_paths: db/migrate
#
#  primary_replica:
#    <<: *default
#    database: <%= Rails.application.credentials.dig(:erm_replica, :database) %>
#    username: <%= Rails.application.credentials.dig(:erm_replica, :username) %>
#    host: <%= Rails.application.credentials.dig(:erm_replica,:host) %>
#    password: <%= Rails.application.credentials.dig(:erm_replica, :password) %>
#    replica: true
#    migrations_paths: db/migrate #only writer database need migrations, rails doesn't run migration for replicas
